### ISSUE TITLE
Don’t use __dirname for the default cache

### ISSUE THREAD

**Issue by Swatinem** [polyfills/ecstacy#11]
Problem:

nlz/ecstacy is installed globally, with sudo.

now I want to run nlz build with a normal user. It fails because the normal user can’t access /usr/lib/node_modules/…/ecstacy/cache/

You should use pwd instead, to make sure a normal user can write to it.

**Comment by jonathanong** [comment]
i think i'm going to cache things as `process.cwd() + '/cache/<module>'` now

**Comment by jonathanong** [comment]
i'm using a tmpdir now. if that fails, let me know.
