### ISSUE TITLE
pass in browsers to autoprefixer

### ISSUE THREAD

**Issue by jonathanong** [polyfills/ecstacy#7]

**Comment by jonathanong** [comment]
no point. just autoprefix everything haha

**Comment by gnimmelf** [comment]
Yes, good idea! 

I was really curious about the ua-detection you mentioned, was worried I might have to start requesting prox.js from the client instead of serving static files precompiled with `nlz`. (But I guess that _is_ the goal somehow?)

**Comment by jonathanong** [comment]
Naw don't do that. Proxy isn't optimized for production
